services:
  matrix-bot:
    build: .
    restart: "no"
    env_file: .env
    environment:
      - TZ=Europe/Paris
    command: ["npm", "run", "dev"]
    volumes:
      - ./data:/app/data
      - ./src:/app/src:ro
